### ISSUE TITLE
Multisig

### ISSUE THREAD

**Issue by jschnauss** [orlp/ed25519#26]
Hello! This is a question or a feature request.

I find this portable library very useful, but has come to a situation where multisig functionality is required. The solution is outlined in the answer to this question:
https://crypto.stackexchange.com/questions/50448/schnorr-signatures-multisignature-support

Considering my specific use cases, the desired functions are:

1. Verify a combined signature of two or more public keys, for instance 𝐴+𝐵 as mentioned in the answer on Stack Exchange.

2. Create a combined signature for one message using multiple key pairs, where all seeds or private keys are known to the signer. (This is mostly required to test the verification in 1. Later on other implementations will create such signatures cooperatively or on their own.)

Maybe this can already be achieved by using the provided functions in the lib in various ways? Any ideas are welcome.

Thank you!

**Comment by orlp** [comment]
Sorry, this would involve non-trivial cryptography which I don't want to implement. My library is mostly a nicer API around the SUPERCOP "ref10" implementation, and I intentionally try not to touch the cryptographic aspects in this library, deferring to the expert authors of that implementation.
