### ISSUE TITLE
Why private_key 64 bits?

### ISSUE THREAD

**Issue by woshizuibangde** [orlp/ed25519#27]
Soory sir:

 i have a confuse that why private key is 64 bits?  the order of G is 2^255 +277....493, so privacy_key shouldnt be one number less order? So why 64 bits?

Thank you!
Wang

**Comment by orlp** [comment]
First, `private_key` is 64 *bytes*, not 64 *bits*. The first 32 bytes store a curve point, and as you can see some bits are ignored/set to make it valid: https://github.com/orlp/ed25519/blob/7fa6712ef5d581a6981ec2b08ee623314cd1d1c4/src/keypair.c#L10

The second 32 bytes store a second portion of the hash of the seed as it's needed.
