### ISSUE TITLE
ed25519 private key should be 32 bytes long. 

### ISSUE THREAD

**Issue by sichunqin** [orlp/ed25519#34]
According to RFC 8032, ed25519 private key should be 32 bytes long. Does the implement comply with the standard?  

The implementation seems not comply with the test vector provided by RFC 8032. Please refer to https://asecuritysite.com/ecc/eddsa5 for the test vector. Thanks.

**Comment by sichunqin** [comment]
I find the reason. Normally 32 bytes seed is used for private key, but the library uses sha-512(seeds) generated result as private key which is 64 bytes long.

**Comment by orlp** [comment]
My library predates RFC 8032 by 4 years.

**Comment by damondd** [comment]
tried to combine a 32-byte private key and a 32-byte public key, sign result is incorrect compared to openssl/wolfssl...
